[package]
name = "pypki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pypki"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.1"
schannel = "0.1.27"
